### ISSUE TITLE
SRU plugin performance issue

### ISSUE THREAD

**Issue by zonapellucida** [xbib/elasticsearch-plugin-sru#7]
I have a rather large dataset, when I do a query like:

curl -XGET 'http://localhost:9200/myIndex/_search'

It returns:

{
  "took" : 117,
  "timed_out" : false,
  "_shards" : {
    "total" : 50,
    "successful" : 50,
    "failed" : 0
  },
  "hits" : {
    "total" : 85873045,
    "max_score" : 1.0,
...

I modified the SRU plugin to also include the took value along with some other timing values to see how long each section takes (Note: my changes doesn't affect the performance of the plugin since I get the same timing results with the plugin without any changes to the source).  My query:

curl -H "Accept: application/json" -XGET "http://localhost:9500/_sru/myIndex?operation=searchRetrieve&version=2.0&query=myField>0"

SRU search results:

{
  "total":85873045,
  "took":2169, 
  "records":[{
  ...
}

Notice that both searches results in 85,873,045 matches.  The normal elasticsearch took value is 117 ms, while the SRU plugin took 2,169 ms.  It appears that the SRU plugin is about 18 times slower than the normal elasticsearch query.  

Looking at the code for:

elasticsearch-plugin-sru/src/main/groovy/org/xbib/elasticsearch/module/sru/SRUHandler.groovy

The took value coincides with my own debug timing from line 210:

SearchResponse searchResponse = client.search(searchRequest).actionGet()

Does the org.elasticsearch.client.Client Object have to establish a connection to the elasticsearch server every time the SRU plugin does an ES search? I am a newbie to groovy, but it looks like 

org.elasticsearch.client.Client client

gets initialized some how in:

elasticsearch-plugin-sru/src/ratpack/Ratpack.groovy

but it is not clear to me if the connection to elasticsearch is somehow cached or if it is reestablished every time the SRU plugin does a search.

In general however, it seems like the SRU plugin has a size-able overhead.  Are there any optimizations that I am missing, or is there something I am doing incorrectly?

**Comment by jprante** [comment]
Can you show the queries you execute? SRU writes them into the log file.

The SRU plugin does not cache or perform tricks, it's just executing the Java API.

**Comment by zonapellucida** [comment]
So that's the other problem I have.  I can never produce a readable sru.log.  

I have tried the two scenarios:

Scenario 1, Leave the elasticsearch-plugin-sru/src/ratpack/log4j2.xml as is:
In this scenario, since the log4j2.xml points to: 
<File name="File" fileName="logs/sru.log" immediateFlush="false"   append="true">
...
I try to create a "logs" folder and set the permissions to 777. My elasticsearch install is in /usr/share/elasticsearch. I tried creating a "logs" folder in /usr/share/elasticsearch/logs, /usr/share/elasticsearch/bin/logs, /var/logs, /var/log/logs, etc... I changed the permissions to 777 for all of these folders, but when I startup elasticsearch I see the following error:

ERROR StatusLogger FileManager (logs/sru.log) java.io.FileNotFoundException: logs/sru.log (No such file or directory)
ERROR StatusLogger Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.FileAppender for element File. java.lang.reflect.InvocationTargetException


Scenario 2, I edit elasticsearch-plugin-sru/src/ratpack/log4j2.xml:
In this scenario, I change the File element to:
<File name="File" fileName="/var/log/elasticsearch/sru.log" immediateFlush="false"   append="true">
...
As expected, /var/log/elasticsearch/sru.log gets generated, however nothing gets written to it


Lastly, I recently tried cloning the elasticsearch-plugin-sru to a new project. I am able to build the project fine and the elasticsearch-plugin-sru-orig-1.5.2.4-plugin.zip artifact gets generated, however, when I try to install the plugin on my ES master instance with the latest source, I get the following error:

org.elasticsearch.ElasticsearchException: no plugins.sru.path set in system properties
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
        at org.xbib.elasticsearch.module.sru.SRUService.doStart(SRUService.groovy:82)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85)
        at org.elasticsearch.node.internal.InternalNode.start(InternalNode.java:244)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:160)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:248)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
[2015-09-28 13:11:06,156][INFO ][node                     ] [Midas] stopping ...


Thanks for your help.

**Comment by zonapellucida** [comment]
NOTE: I am using eclipse to run the gradle build:

clean buildPluginZip

**Comment by zonapellucida** [comment]
I also tried installing gradle 2.6 and running the command:

gradle -b elasticsearch-plugin-sru/build.gradle clean buildPluginZip

I still get the above error : 

org.elasticsearch.ElasticsearchException: no plugins.sru.path set in system properties

**Comment by zonapellucida** [comment]
OK, I just went ahead and hard coded the path to the "plugins.sru.path" value in 

elasticsearch-plugin-sru/src/main/groovy/org/xbib/elasticsearch/module/sru/SRUService.groovy.doStart():

...
        if (app == null) {
			System.setProperty("plugins.sru.path", "/usr/share/elasticsearch/plugins/sru/elasticsearch-plugin-sru-1.5.2.4.jar");

...

I also changed my elasticsearch-plugin-sru/src/ratpack/log4j2.xml to point to an absolute path for the sru.log file, but the sru.log file never gets written to after an sru search.

**Comment by jprante** [comment]
Can you please try 1.5.2.5, I have added a workaround.

Please remove groovy 2.4.0 jar in ES before start, like this

```
Jorg-Prantes-MacBook-Pro:elasticsearch-1.5.2 joerg$ rm lib/groovy-all-2.4.0.jar 
Jorg-Prantes-MacBook-Pro:elasticsearch-1.5.2 joerg$ ./bin/elasticsearch -Des.cluster.name=joerg
[2015-09-29 10:20:32,791][INFO ][node                     ] [Enchantress] version[1.5.2], pid[29200], build[62ff986/2015-04-27T09:21:06Z]
[2015-09-29 10:20:32,792][INFO ][node                     ] [Enchantress] initializing ...
[2015-09-29 10:20:33,025][INFO ][plugins                  ] [Enchantress] loaded [sru], sites []
[2015-09-29 10:20:34,745][INFO ][node                     ] [Enchantress] initialized
[2015-09-29 10:20:34,745][INFO ][node                     ] [Enchantress] starting ...
[10:20:35,915][INFO ][ratpack.server.RatpackServer][main] Ratpack started for http://localhost:5051
[2015-09-29 10:20:35,952][INFO ][transport                ] [Enchantress] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.1.1.6:9300]}
[2015-09-29 10:20:35,964][INFO ][discovery                ] [Enchantress] joerg/zAPeVdHATSuicLkJWEJPpw
[2015-09-29 10:20:39,735][INFO ][cluster.service          ] [Enchantress] new_master [Enchantress][zAPeVdHATSuicLkJWEJPpw][Jorg-Prantes-MacBook-Pro.local][inet[/10.1.1.6:9300]], reason: zen-disco-join (elected_as_master)
[2015-09-29 10:20:39,752][INFO ][http                     ] [Enchantress] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.1.1.6:9200]}
[2015-09-29 10:20:39,752][INFO ][node                     ] [Enchantress] started
[2015-09-29 10:20:39,756][INFO ][gateway                  ] [Enchantress] recovered [0] indices into cluster_state
```

**Comment by zonapellucida** [comment]
I pulled the latest source and it still builds 1.5.2.4. Did you commit and push your changes?

**Comment by jprante** [comment]
Sorry, I just pushed the binary.

Now the change is committed and tagged with 1.5.2.5

**Comment by zonapellucida** [comment]
I pulled your latest changes, and I was able to build:

elasticsearch-plugin-sru-1.5.2.5-plugin.zip

However, I am still having issues with the sru.log.

If I make no changes and just build the zip artifact, after installing the new elasticsearch-plugin-sru-1.5.2.5-plugin.zip plugin, I get the same error when restarting the elasticsearch server:

ERROR StatusLogger FileManager (logs/sru.log) java.io.FileNotFoundException: logs/sru.log (No such file or directory)
ERROR StatusLogger Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.FileAppender for element File. java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:135)

If I first edit elasticsearch-plugin-sru/src/ratpack/log4j2.xml and put and change the <File from:

<File name="File" fileName="logs/sru.log" immediateFlush="false"   append="true">

to:

<File name="File" fileName="/var/log/elasticsearch/sru.log" immediateFlush="false"   append="true">

/var/log/elasticsearch/sru.log gets created without any elasticsearch server errors upon restart, but it's contents are empty.  Even after issuing multiple elasticsearch queries, /var/log/elasticsearch/sru.log always remains empty.  

Am I doing something wrong?
